services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no"]
    volumes:
      - /local-data/:/data
  
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - 8001:5540
    depends_on:
      - redis
    volumes:
      - redisinsight-data:/db
  
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
     - 9092:9092
    
  backend2:
    build:
      context: ./backend2   # Contexto de construcción relativo a donde está el docker-compose.yml
    depends_on:             # Correcta estructura para depends_on
      - redis
      - broker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
volumes:
  redisinsight-data: